In [1]:
!python --version

Python 3.14.5

The system cannot find the path specified.

## ___World Checklist of Vascular Plants (WCVP) homotypic synonyms___
----------------

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# look up https://diatoms.org/news/faq-what-are-homotypic-and-heterotypic-synonyms for homotypic synonyms vs heterotypic synonyms

In [4]:
# World Checklist of Vascular Plants (WCVP) dataset from => https://sftp.kew.org/pub/data-repositories/WCVP/

wcvp = pd.read_csv(r"../../data/chapter2/wcvp/wcvp_names.csv", low_memory=False, sep='|', true_values=['T'])

WCVP_COLUMNS = [
    "taxon_name", # full binominal name
    "plant_name_id", # World Checklist of Vascular Plants (WCVP) identifier
    "accepted_plant_name_id", # the ID of the accepted name of this taxon. Where the taxon_status is "Accepted", this will be identical to the plant_name_id value. May be empty if taxon status is unplaced, ilegitimate, or in some cases where the accepted name is not a vascular plant (e.g. a moss, alga or animal).
    "basionym_plant_name_id", # ID of the original name that taxon_name was derived from. If there is a parenthetical author it is a basionym. If there is a replaced synonym author it is a replaced synonym. If empty there have been no name changes. 
    "taxon_status", # indication of nomenclatural status and taxonomic opinion regarding the name
    "homotypic_synonym" # boolan indicating if the name is a homotypic synonym
]

In [5]:
# only pick the records that are homotypic synonyms; i.e. (taxon_status=="Synonym") and (homotypic_synonym==True)

synonym_pairs = wcvp.loc[:, WCVP_COLUMNS].query(r"taxon_status=='Synonym' and homotypic_synonym and (plant_name_id!=accepted_plant_name_id)").loc[:, ("taxon_name", "plant_name_id", "accepted_plant_name_id")]
synonym_pairs = synonym_pairs.astype({"plant_name_id": int, "accepted_plant_name_id": int}).reset_index(drop=True)

In [6]:
# replace the WCVP identifiers with binominal names

wcvp_synonyms_lookup_table = pd.merge(left=synonym_pairs, left_on="accepted_plant_name_id", right=wcvp.loc[:, WCVP_COLUMNS], right_on="plant_name_id", how="left", suffixes=("_syn", '')).loc[:, ("taxon_name", "taxon_name_syn")]
wcvp_synonyms_lookup_table

                     taxon_name                              taxon_name_syn
0            Caladenia minorata                         Caladenia glossodia
1           Chiloglottis gunnii                            Caladenia gunnii
2          Volkameria acerbiana                     Clerodendrum acerbianum
3       Veronica sibthorpioides              Cochlidiosperma sibthorpioides
4       Veronica sibthorpioides  Veronica hederifolia subsp. sibthorpioides
...                         ...                                         ...
281047     Wedelia subpetiolata                        Aspilia subpetiolata
281048        Wedelia tomentosa                           Aspilia tomentosa
281049    Wedelia trichostephia                      Seruneum trichostephia
281050    Wedelia trichostephia                       Trichostemma hispidum
281051        Wedelia warmingii                           Aspilia warmingii

[281052 rows x 2 columns]

In [9]:
wcvp_synonyms_lookup_table.rename({"taxon_name": "name", "taxon_name_syn": "synonym"}, axis=1)

                           name                                     synonym
0            Caladenia minorata                         Caladenia glossodia
1           Chiloglottis gunnii                            Caladenia gunnii
2          Volkameria acerbiana                     Clerodendrum acerbianum
3       Veronica sibthorpioides              Cochlidiosperma sibthorpioides
4       Veronica sibthorpioides  Veronica hederifolia subsp. sibthorpioides
...                         ...                                         ...
281047     Wedelia subpetiolata                        Aspilia subpetiolata
281048        Wedelia tomentosa                           Aspilia tomentosa
281049    Wedelia trichostephia                      Seruneum trichostephia
281050    Wedelia trichostephia                       Trichostemma hispidum
281051        Wedelia warmingii                           Aspilia warmingii

[281052 rows x 2 columns]

In [10]:
wcvp_synonyms_lookup_table.rename({"taxon_name": "name", "taxon_name_syn": "synonym"}, axis=1).to_csv(r"../../data/chapter2/wcvp/synonyms.csv", index=False)